// Every icon in the app comes from Lucide (lucide.dev). Components use the
// Lucide icons directly; data that has to stay plain — badges, AI ideas,
// split kinds, anything built in lib/ or sent over the wire — names its icon
// with one of these keys (Lucide's own names) and is drawn with <Icon>.

import {
  Activity,
  Anchor,
  ArrowLeftRight,
  Bomb,
  Box,
  CassetteTape,
  ChartNoAxesColumnIncreasing,
  CircleDashed,
  CloudFog,
  CloudRain,
  Disc3,
  DoorOpen,
  Drum,
  FastForward,
  Flag,
  Flame,
  Gem,
  Guitar,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  Link,
  Magnet,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  MicVocal,
  Monitor,
  Moon,
  Music,
  Orbit,
  PartyPopper,
  Piano,
  Pickaxe,
  Puzzle,
  Rabbit,
  Radio,
  RefreshCw,
  Repeat,
  Repeat1,
  Rocket,
  Scale,
  Scissors,
  Shuffle,
  SlidersHorizontal,
  SlidersVertical,
  Smartphone,
  Sparkles,
  Spline,
  Stethoscope,
  Target,
  ThumbsUp,
  Timer,
  TrendingUp,
  Users,
  Volume2,
  Waves,
  Zap,
  type LucideProps,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  anchor: Anchor,
  "arrow-left-right": ArrowLeftRight,
  bomb: Bomb,
  box: Box,
  "cassette-tape": CassetteTape,
  "chart-no-axes-column-increasing": ChartNoAxesColumnIncreasing,
  "circle-dashed": CircleDashed,
  "cloud-fog": CloudFog,
  "cloud-rain": CloudRain,
  "disc-3": Disc3,
  "door-open": DoorOpen,
  drum: Drum,
  "fast-forward": FastForward,
  flag: Flag,
  flame: Flame,
  gem: Gem,
  guitar: Guitar,
  hammer: Hammer,
  handshake: Handshake,
  headphones: Headphones,
  heart: Heart,
  "heart-pulse": HeartPulse,
  link: Link,
  magnet: Magnet,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  mic: Mic,
  "mic-vocal": MicVocal,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  orbit: Orbit,
  "party-popper": PartyPopper,
  piano: Piano,
  pickaxe: Pickaxe,
  puzzle: Puzzle,
  rabbit: Rabbit,
  radio: Radio,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "repeat-1": Repeat1,
  rocket: Rocket,
  scale: Scale,
  scissors: Scissors,
  shuffle: Shuffle,
  "sliders-horizontal": SlidersHorizontal,
  "sliders-vertical": SlidersVertical,
  smartphone: Smartphone,
  sparkles: Sparkles,
  spline: Spline,
  stethoscope: Stethoscope,
  target: Target,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  "trending-up": TrendingUp,
  users: Users,
  "volume-2": Volume2,
  waves: Waves,
  zap: Zap,
};

export type IconName = keyof typeof ICONS;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Glyph = ICONS[name];
  return <Glyph {...props} />;
}

const MEDAL_COLORS = ["text-amber-400", "text-slate-300", "text-orange-400"];

/** Gold, silver or bronze for the top three; anyone else just gets their number. */
export function PlaceMedal({ rank, className = "" }: { rank: number; className?: string }) {
  if (rank > MEDAL_COLORS.length) return <>{rank}</>;
  return <Medal className={`${MEDAL_COLORS[rank - 1]} ${className}`} role="img" aria-label={`#${rank}`} aria-hidden={false} />;
}
